# Generated by Django 5.2.7 on 2025-10-06 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('NEW_ID', 'New ID'), ('ID_RENEWAL', 'ID Renewal'), ('BIRTH_CERTIFICATE', 'Birth Certificate')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('READY', 'Ready for Pickup'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('resident_address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('existing_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_for_renewal', models.CharField(blank=True, max_length=255, null=True)),
                ('child_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('father_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='applications/photos/')),
                ('residence_proof', models.FileField(blank=True, null=True, upload_to='applications/proofs/')),
                ('old_id_card', models.FileField(blank=True, null=True, upload_to='applications/old_ids/')),
                ('hospital_proof', models.FileField(blank=True, null=True, upload_to='applications/hospital_proofs/')),
                ('parent_id', models.FileField(blank=True, null=True, upload_to='applications/parent_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
