# Generated by Django 5.2.7 on 2025-10-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birth_certificate_photo',
            field=models.FileField(blank=True, null=True, upload_to='applications/birth_photos/'),
        ),
    ]
